#!/bin/sh

# Creates local snapshots for ES indices and takes care of creating
# weekly backups for the snapshot directory.
#
# For this script to work, ES snapshots should be configured:
# * (/etc/elasticsearch/elasticsearch.yml) path.repo: $base_dir/$data_dir
# * mkdir -p $base_dir/$data_dir
# * chown elasticsearch:elasticsearch $base_dir/$data_dir
# * service elasticsearch restart
# * cat <<EOF | curl -X PUT 'http://127.0.0.1:9200/_snapshot/backup?pretty' -H 'Content-Type: application/json' -d@-
# {
#   "type": "fs",
#   "settings": {
#       "compress" : true,
#       "location": "$base_dir/$data_dir"
#   }
# }
# EOF

base_dir=/var/es
data_dir=snapshot
backup_dir="$base_dir"/backup/weekly


[ -d "$backup_dir" ] \
  || mkdir -p -m 0700 "$backup_dir" \
  || exit 1

backup_name="${backup_dir}/${data_dir}.tar.gz"

create_snapshot() {
  snapshot_name=`date +%Y%m%d`
  response=`curl -X PUT "http://127.0.0.1:9200/_snapshot/backup/${snapshot_name}?pretty&wait_for_completion=true"`
  code=$?
  error=`echo "$response" | jq ".error"`

  [ $code -ne 0 -o "$error" != "null" ] \
    && { echo "Failed to create ES snapshot." >&2 ;
         exit 1;
       }
}

create_snapshot || exit $?

# Rotate backup files
logrotate "$0".logrotate

# Create backup only if the previous one was rotated
[ -f "$backup_name" ] && exit 0

# Create backup file
tar -C "$base_dir" -zcf "$backup_name" "$data_dir"
EXIT_CODE=$?

[ "$EXIT_CODE" -ne 0 ] \
  && { echo "Failed to create backup file for ES data ($EXIT_CODE)." >&2 ;
       exit "$EXIT_CODE";
     }

exit 0
