#!/usr/bin/env bash

[ -z "$COMPARE" ] && COMPARE=YES

base_dir=$(readlink -f $(dirname "$0"))

lib=$base_dir/../shell_lib
. $lib/update_sample
COMPARE_SAMPLES=$COMPARE

for name in datasets tasks; do
  sample=$base_dir/output/$name.ndjson
  cat $base_dir/input/$name.ndjson | $base_dir/run.sh > $sample.new
  update_sample $sample{,.new}
done
