language: python
python:
    - 2.7

notifications:
    email: false

before_install:
    - pip install pep8

script:
    - errors=`find . -name "*.py" -exec pep8 --ignore W503,W292 {} \; `
    - num_errors=`echo -n "$errors" | wc -l`
    - |
        if [ $num_errors -eq 0 ]; then
          true 
        else
          echo "$errors"
          false 
        fi

