notifications:
    email: false

jobs:
  include:
    - stage: python_check
      language: python
      python: 2.7
      before_install:
        - pip install pycodestyle

      script:
        - errors=`find . -name "*.py" -exec pycodestyle --ignore W503,W292 {} \; `
        - |
            if [ -z "$errors" ]; then
              true
            else
              echo "$errors"
              false
            fi

    - stage: python_check
      language: python
      python: 2.7

      script:
        - errors=`find . -name "*.py" -exec python -m py_compile {} \; 2>&1`
        - |
            if [ -z "$errors" ]; then
              true
            else
              echo "$errors"
              false
            fi

    - stage: README_checks
      language: minimal
      name: "Line length"

      script:
        - |
          e=0
          while read f; do
            r=`git diff HEAD^ -- "$f" | grep -v "^+++ b/$f" | grep -e '^+.\{81,\}'`;

            if [ $? -eq 0 ];then
              echo "Very long line(s) in $f:" 
              echo "$r" | sed -e 's/^+//' | while IFS= read -r l; do
                grep -n "^$l\$" -- "$f"
              done
              e=1
            fi
          done <<< $(git diff --name-only HEAD^ | grep 'README$')
          exit $e

    - stage: README_checks
      language: minimal
      name: "Tabs"

      script:
        - |
          e=0
          while read f; do
            r=`git diff HEAD^ -- "$f" | grep -v "^+++ b/$f" | grep -P '^\+.*?\t+.*'`;

            if [ $? -eq 0 ];then
              echo "Tabs found in $f:"
              echo "$r" | sed -e 's/^+//' | while IFS= read -r l; do
                grep -n "^$l\$" -- "$f"
              done
              e=1
            fi
          done <<< $(git diff --name-only HEAD^ | grep 'README$')
          exit $e

    - stage: README_checks
      language: minimal
      name: "Trailing spaces"

      script:
        - |
          e=0
          while read f; do
            r=`git diff HEAD^ -- "$f" | grep -v "^+++ b/$f" | grep -e '^+.*\s\+$'`;

            if [ $? -eq 0 ];then
              echo "Trailing spaces found $f:"
              echo "$r" | sed -e 's/^+//' | while IFS= read -r l; do
                grep -n "^$l\$" -- "$f"
              done
              e=1
            fi
          done <<< $(git diff --name-only HEAD^ | grep 'README$')
          exit $e
