notifications:
    email: false

jobs:
  include:
    - stage: python_check
      language: python
      python: 2.7
      before_install:
        - pip install pycodestyle

      script:
        - errors=`find . -name "*.py" -exec pycodestyle --ignore W503,W292 {} \; `
        - |
            if [ -z "$errors" ]; then
              true
            else
              echo "$errors"
              false
            fi

    - stage: python_check
      language: python
      python: 2.7

      script:
        - errors=`find . -name "*.py" -exec python -m py_compile {} \; 2>&1`
        - |
            if [ -z "$errors" ]; then
              true
            else
              echo "$errors"
              false
            fi

    - stage: README_line_length
      language: minimal

      script:
        - |
          e=0
          git diff --name-only HEAD^ | grep 'README$' | while read f; do
            r=`git diff HEAD^ -- "$f" | grep -v "^+++ b/$f" | grep -ne '^+.\{81,\}' | sed -e 's/^\([0-9]*:\)+/\1/'`;
            if [ $? -eq 0 ];then
              echo "Very long line(s) in $f:"
              echo "$r"
              e=1
            fi
          done
          exit $e
