#!/usr/bin/env bash

base_dir=$(readlink -f $(dirname "$0"))

sample=$base_dir/output/sample.ndjson

git checkout $sample
mv $sample{,.bak}

$base_dir/stage.py -d s $base_dir/input/sample.ndjson > $sample
