#!/bin/bash -l

DEBUG=

base_dir=$( cd "$(dirname "$(readlink -f "$0")")"; pwd)
lib="$base_dir/../shell_lib"

# Directories with configuration files
[ -n "$DATA4ES_CONSISTENCY_CONFIG_PATH" ] && \
    CONFIG_PATH="$DATA4ES_CONSISTENCY_CONFIG_PATH" || \
    CONFIG_PATH="${base_dir}/../config:${base_dir}/../../../Elasticsearch/config"

source $lib/get_config
source $lib/eop_filter
source $lib/run_stage

# Oracle
cfg009=`get_config "consistency009.cfg"`
cmd_009="$base_dir/../009_oracleConnector/Oracle2JSON.py --config $cfg009"

# Formatting
cmd_016="$base_dir/../016_task2es/task2es.py -m s"

# ES
cfg_es=`get_config "es"`
cmd_071="$base_dir/../071_esConsistency/consistency.py -m s --conf $cfg_es"

while [ -n "$1" ]; do
  case $1 in
    --debug)
      DEBUG=1;;
    *)
      break;;
  esac
  shift
done


# 0             | 1               | 2
# | 3                | 4
run_stage '009' | run_stage '016' | eop_filter \
  |  run_stage '071' | eop_filter

status="${PIPESTATUS[3]}"

[ $status -eq 0 ] && status_info=OK || status_info=FAIL
log INFO "Consistency check finished, status: $status_info"

exit $status
