#!/usr/bin/env bash

[ -z "$COMPARE" ] && COMPARE=YES

base_dir=$(readlink -f $(dirname "$0"))

lib=$base_dir/../shell_lib
. $lib/update_sample
COMPARE_SAMPLES=$COMPARE

sample=$base_dir/output/datasets.ndjson

key=$RUCIO_HOME/auth/key.pem
crt=$RUCIO_HOME/auth/crt.pem
$base_dir/amiDatasets.py --userkey $key --usercert $crt -d s $base_dir/input/datasets.ndjson > $sample.new

update_sample $sample{,.new}
