#!/usr/bin/env bash

base_dir=$(readlink -f $(dirname "$0"))

sample=$base_dir/output/datasets.ndjson

git checkout $sample
mv $sample{,.bak}

$base_dir/datasets_format.py -d s $base_dir/input/output_datasets.ndjson > $sample
