#!/usr/bin/env bash

# Utility to update data samples for dataflow stages
#
# data4es process overview:
#
# 009 ---> 091(in) ---> 016 ---> 019 ---> 069
#   \                                     /
#    \---> 091(out) ---> 093 ---> 095 ---/

base_dir=$(readlink -f $(dirname "$0"))

echo "Updating samples for:"
for stage in 009 091 016 019 093 095; do
    echo "Stage ${stage}..."
    $base_dir/../${stage}_*/update_sample \
      || { echo "Failed to update sample for Stage $stage." >&2 && exit 1; }
done
