#!/bin/bash -l

DEBUG=

base_dir=$( cd "$(dirname "$(readlink -f "$0")")"; pwd)

# Directories with configuration files
[ -n "$DATA4ES_CONSISTENCY_CONFIG_PATH" ] && \
    CONFIG_PATH="$DATA4ES_CONSISTENCY_CONFIG_PATH" || \
    CONFIG_PATH="${base_dir}/../config:${base_dir}/../../Elasticsearch/config"

# Find configuration file in $CONFIG_PATH
get_config() {
  [ -z "$1" ] && echo "get_config(): no arguments passed." && return 1
  dirs=$CONFIG_PATH
  while [ -n "$dirs" ]; do
    dir=${dirs%%:*}
    [ "$dirs" = "$dir" ] && \
        dirs='' || \
        dirs="${dirs#*:}"
    [ -f "${dir}/${1}" ] && readlink -f "${dir}/${1}" && return 0
  done
}

# EOP filter (required due to the unconfigurable EOP marker in pyDKB)
eop_filter() {
  sed -e"s/\\x00//g"
}

# Oracle
cfg009=`get_config "consistency009.cfg"`
cmd_009="$base_dir/../009_oracleConnector/Oracle2JSON.py --config $cfg009"
[ -n "$DEBUG" ] &&
  err009="009.err" ||
    err009=/dev/null

# Formatting
cmd_016="$base_dir/../016_task2es/task2es.py -m s"
[ -n "$DEBUG" ] &&
  err016="016.err" ||
    err016=/dev/null

# ES
cfg_es=`get_config "es"`
cmd_069="$base_dir/../069_upload2es/consistency.py -m s --conf $cfg_es"

$cmd_009 2>"$err009" | $cmd_016 2>"$err016" | eop_filter | $cmd_069 >/dev/null
