#!/usr/bin/env bash

base_dir=$( cd "$(dirname "$(readlink -f "$0")")"; pwd)
pidfile=$base_dir/$(basename "$0" | cut -d- -f1).pid

[ -r "$pidfile" ] || exit 0
pids=`cat $pidfile`

while [ -n "$1" ]; do
  case "$1" in
    --hard)
      MODE="HARD"
      WAIT=1;;
    --soft)
      MODE="SOFT";;
    --wait)
      WAIT=1;;
    --)
      shift
      break;;
    -*)
      echo "Unknown option: $1" >&2;;
    *)
      break;;
  esac
  shift
done

[ "x$MODE" = "xSOFT" ] \
  && kill `echo "$pids" | grep 'source' | cut -d' ' -f 1` >/dev/null 2>&1 \
  || kill `echo $pids | sed -e"s/source//"` >/dev/null 2>&1


sleep 1

if [ -n "$WAIT" ]; then
  while [ -n "$pids" ]; do
    new_pids=""
    for pid in $pids; do
      [[ "$pid" =~ ^[0-9]+$ ]] \
        && new_pids="$new_pids
$(ps axo pid | grep "^\s*${pid}$")"
    done
    pids=$new_pids
    sleep 1
  done
  rm $pidfile 2>/dev/null
else
  for pid in $pids; do
    ps ao pid | grep '^\s*$pid\s' >> ${pidfile}.tmp
  done
  mv ${pidfile}.tmp $pidfile 2>/dev/null
fi

exit 0
