#!/usr/bin/env bash

[ -z "$COMPARE" ] && COMPARE=YES

base_dir=$(readlink -f $(dirname "$0"))

lib=$base_dir/../shell_lib
. $lib/update_sample
COMPARE_SAMPLES=$COMPARE

cfg=$base_dir/../config/009.cfg
offset=$base_dir/../config/009.offset
sample=$base_dir/output/sample.ndjson

sed -e's/^initial = .*$/initial = 09-05-2016 12:12:00/' \
    -e's/^final = .*$/final = 09-05-2016 13:32:30/' \
    -i.bak $cfg

rm -f $offset

$base_dir/Oracle2JSON.py --config $cfg --mode SQUASH > $sample.new

update_sample $sample{,.new}
