#!/usr/bin/env bash

base_dir=$(readlink -f $(dirname "$0"))

cfg=$base_dir/../config/009.cfg
offset=$base_dir/../config/009.offset
sample=$base_dir/output/sample.ndjson

sed -e's/^initial = .*$/initial = 09-05-2016 12:12:00/' \
    -e's/^final = .*$/final = 09-05-2016 13:32:30/' \
    -i.bak $cfg

rm -f $offset

git checkout $sample
mv $sample{,.bak}

$base_dir/Oracle2JSON.py --config $cfg --mode SQUASH > $sample
