#!/usr/bin/env bash

base_dir=$(readlink -f $(dirname "$0"))

for type in input output; do
  sample=$base_dir/output/${type}_datasets.ndjson
  git checkout $sample
  mv $sample{,.bak}
  $base_dir/datasets_processing.py -d s $base_dir/input/sample.ndjson > $sample
done
