#!/usr/bin/env bash

[ -z "$COMPARE" ] && COMPARE=YES

base_dir=$(readlink -f $(dirname "$0"))

lib=$base_dir/../shell_lib
. $lib/update_sample
COMPARE_SAMPLES=$COMPARE

sample=$base_dir/output/sample.ndjson

$base_dir/task2es.py -d s $base_dir/input/sample.ndjson > $sample.new

update_sample $sample{,.new}
